// This file has been generated by zoltan (https://github.com/jac3km4/zoltan)

#define ZOLTAN_STRINGISE(N) #N
#define ZOLTAN_EXPAND_THEN_STRINGISE(N) ZOLTAN_STRINGISE(N)
#define __LINE_STR__ ZOLTAN_EXPAND_THEN_STRINGISE(__LINE__)

#ifndef CreateCRTTIArrayTypeFromClass_Addr
#define CreateCRTTIArrayTypeFromClass_Addr 0x20A490
#endif
#ifndef CreateCRTTIHandleTypeFromClass_Addr
#define CreateCRTTIHandleTypeFromClass_Addr 0x20A580
#endif
#ifndef CreateCRTTIRaRefTypeFromClass_Addr
#define CreateCRTTIRaRefTypeFromClass_Addr 0x20A750
#endif
#ifndef CreateCRTTIWeakHandleTypeFromClass_Addr
#define CreateCRTTIWeakHandleTypeFromClass_Addr 0x20A920
#endif
#ifndef CreateStaticEffect_Addr
#define CreateStaticEffect_Addr 0x14A19A0
#endif
#ifndef Entity_InitializeComponents_Addr
#define Entity_InitializeComponents_Addr 0x105DFD0
#endif
#ifndef FPPCameraUpdate_Addr
#define FPPCameraUpdate_Addr 0x172BD30
#endif
#ifndef FourWheelTorque_Addr
#define FourWheelTorque_Addr 0x1D4DA20
#endif
#ifndef GetMatrixFromOrientation_Addr
#define GetMatrixFromOrientation_Addr 0x1D3F60
#endif
#ifndef LoadResRefT_Addr
#define LoadResRefT_Addr 0x20E8C0
#endif
#ifndef LookupLocalizedString_Addr
#define LookupLocalizedString_Addr 0x7093F0
#endif
#ifndef PhysicsUnkStructVelocityUpdate_Addr
#define PhysicsUnkStructVelocityUpdate_Addr 0x1D20160
#endif
#ifndef ProcessAirResistance_Addr
#define ProcessAirResistance_Addr 0x1D4D740
#endif
#ifndef ProcessScriptTypes_Addr
#define ProcessScriptTypes_Addr 0x281390
#endif
#ifndef RollFactorTorqueThing_Addr
#define RollFactorTorqueThing_Addr 0x1D6E3E0
#endif
#ifndef SetLocalizedTextString_Addr
#define SetLocalizedTextString_Addr 0x709460
#endif
#ifndef TPPCameraStats_Update_Addr
#define TPPCameraStats_Update_Addr 0x1D06600
#endif
#ifndef VehicleHelperUpdate_Addr
#define VehicleHelperUpdate_Addr 0x1D51500
#endif
#ifndef VehicleObject_ProcessWeapons_Addr
#define VehicleObject_ProcessWeapons_Addr 0x1C9F220
#endif
#ifndef VehicleUpdateOrientationWithPID_Addr
#define VehicleUpdateOrientationWithPID_Addr 0x1CACFD0
#endif
#ifndef vehicle_PhysicsStructUpdate_Addr
#define vehicle_PhysicsStructUpdate_Addr 0x1D20B70
#endif
