// This file has been generated by zoltan (https://github.com/jac3km4/zoltan)

#define ZOLTAN_STRINGISE(N) #N
#define ZOLTAN_EXPAND_THEN_STRINGISE(N) ZOLTAN_STRINGISE(N)
#define __LINE_STR__ ZOLTAN_EXPAND_THEN_STRINGISE(__LINE__)

#ifndef CreateCRTTIArrayTypeFromClass_Addr
#define CreateCRTTIArrayTypeFromClass_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: CreateCRTTIArrayTypeFromClass_Addr"                  \
              "is 0 - Zoltan found count mismatch for CreateCRTTIArrayTypeFromClass (8)\")")
#endif
#ifndef CreateCRTTIHandleTypeFromClass_Addr
#define CreateCRTTIHandleTypeFromClass_Addr                                                                            \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: CreateCRTTIHandleTypeFromClass_Addr"                 \
              "is 0 - Zoltan found count mismatch for CreateCRTTIHandleTypeFromClass (6)\")")
#endif
#ifndef CreateCRTTIRaRefTypeFromClass_Addr
#define CreateCRTTIRaRefTypeFromClass_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: CreateCRTTIRaRefTypeFromClass_Addr"                  \
              "is 0 - Zoltan found count mismatch for CreateCRTTIRaRefTypeFromClass (6)\")")
#endif
#ifndef CreateCRTTIWeakHandleTypeFromClass_Addr
#define CreateCRTTIWeakHandleTypeFromClass_Addr                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: CreateCRTTIWeakHandleTypeFromClass_Addr"             \
              "is 0 - Zoltan found count mismatch for CreateCRTTIWeakHandleTypeFromClass (6)\")")
#endif
#ifndef CreateStaticEffect_Addr
#define CreateStaticEffect_Addr 0x3B2630
#endif
#ifndef Entity_InitializeComponents_Addr
#define Entity_InitializeComponents_Addr 0x1F9820
#endif
#ifndef FPPCameraUpdate_Addr
#define FPPCameraUpdate_Addr 0x535EBC
#endif
#ifndef FourWheelTorque_Addr
#define FourWheelTorque_Addr                                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: FourWheelTorque_Addr"                                \
              "is 0 - Zoltan found no matches for FourWheelTorque\")")
#endif
#ifndef GameSetting_EnableSmoothWheelContacts_Addr
#define GameSetting_EnableSmoothWheelContacts_Addr                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: GameSetting_EnableSmoothWheelContacts_Addr"          \
              "is 0 - Zoltan found no matches for GameSetting::EnableSmoothWheelContacts\")")
#endif
#ifndef GameSetting_physicsCCD_Addr
#define GameSetting_physicsCCD_Addr                                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: GameSetting_physicsCCD_Addr"                         \
              "is 0 - Zoltan found no matches for GameSetting::physicsCCD\")")
#endif
#ifndef GetLocationFromOffset_Addr
#define GetLocationFromOffset_Addr 0x598A14
#endif
#ifndef GetMatrixFromOrientation_Addr
#define GetMatrixFromOrientation_Addr 0x146AA4
#endif
#ifndef GetYaw_Addr
#define GetYaw_Addr 0xEEABC4
#endif
#ifndef LoadResRefT_Addr
#define LoadResRefT_Addr                                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: LoadResRefT_Addr"                                    \
              "is 0 - Zoltan found no matches for LoadResRefT\")")
#endif
#ifndef LookupLocalizedString_Addr
#define LookupLocalizedString_Addr                                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: LookupLocalizedString_Addr"                          \
              "is 0 - Zoltan found no matches for LookupLocalizedString\")")
#endif
#ifndef PhysicsUnkStructVelocityUpdate_Addr
#define PhysicsUnkStructVelocityUpdate_Addr 0x17ADC4
#endif
#ifndef ProcessAirResistance_Addr
#define ProcessAirResistance_Addr                                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: ProcessAirResistance_Addr"                           \
              "is 0 - Zoltan found no matches for ProcessAirResistance\")")
#endif
#ifndef ProcessScriptTypes_Addr
#define ProcessScriptTypes_Addr                                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: ProcessScriptTypes_Addr"                             \
              "is 0 - Zoltan found no matches for ProcessScriptTypes\")")
#endif
#ifndef RollFactorTorqueThing_Addr
#define RollFactorTorqueThing_Addr                                                                                     \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: RollFactorTorqueThing_Addr"                          \
              "is 0 - Zoltan found no matches for RollFactorTorqueThing\")")
#endif
#ifndef SetLocalizedTextString_Addr
#define SetLocalizedTextString_Addr                                                                                    \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: SetLocalizedTextString_Addr"                         \
              "is 0 - Zoltan found no matches for SetLocalizedTextString\")")
#endif
#ifndef TPPCameraStats_Update_Addr
#define TPPCameraStats_Update_Addr 0x1FD5720
#endif
#ifndef UpdatePitch_Addr
#define UpdatePitch_Addr 0x598F3C
#endif
#ifndef VehicleHelperUpdate_Addr
#define VehicleHelperUpdate_Addr                                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: VehicleHelperUpdate_Addr"                            \
              "is 0 - Zoltan found no matches for VehicleHelperUpdate\")")
#endif
#ifndef VehicleUpdateOrientationWithPID_Addr
#define VehicleUpdateOrientationWithPID_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: VehicleUpdateOrientationWithPID_Addr"                \
              "is 0 - Zoltan found no matches for VehicleUpdateOrientationWithPID\")")
#endif
#ifndef vehicle_PhysicsStructUpdate_Addr
#define vehicle_PhysicsStructUpdate_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicle_PhysicsStructUpdate_Addr"                    \
              "is 0 - Zoltan found no matches for vehicle::PhysicsStructUpdate\")")
#endif
