// This file has been generated by zoltan (https://github.com/jac3km4/zoltan)

#define ZOLTAN_STRINGISE(N) #N
#define ZOLTAN_EXPAND_THEN_STRINGISE(N) ZOLTAN_STRINGISE(N)
#define __LINE_STR__ ZOLTAN_EXPAND_THEN_STRINGISE(__LINE__)

#ifndef CreateCRTTIArrayTypeFromClass_Addr
#define CreateCRTTIArrayTypeFromClass_Addr 0x20A490
#endif
#ifndef CreateCRTTIHandleTypeFromClass_Addr
#define CreateCRTTIHandleTypeFromClass_Addr 0x20A580
#endif
#ifndef CreateCRTTIRaRefTypeFromClass_Addr
#define CreateCRTTIRaRefTypeFromClass_Addr 0x20A750
#endif
#ifndef CreateCRTTIWeakHandleTypeFromClass_Addr
#define CreateCRTTIWeakHandleTypeFromClass_Addr 0x20A920
#endif
#ifndef CreateStaticEffect_Addr
#define CreateStaticEffect_Addr 0x14A19A0
#endif
#ifndef Entity_InitializeComponents_Addr
#define Entity_InitializeComponents_Addr 0x105DFD0
#endif
#ifndef ExecuteCommand_Addr
#define ExecuteCommand_Addr 0x2C23D70
#endif
#ifndef FPPCameraUpdate_Addr
#define FPPCameraUpdate_Addr 0x172BD30
#endif
#ifndef FourWheelTorque_Addr
#define FourWheelTorque_Addr 0x1D4DA20
#endif
#ifndef GetMatrixFromOrientation_Addr
#define GetMatrixFromOrientation_Addr 0x1D3F60
#endif
#ifndef LoadResRefT_Addr
#define LoadResRefT_Addr 0x20E8C0
#endif
#ifndef LookupLocalizedString_Addr
#define LookupLocalizedString_Addr 0x7093F0
#endif
#ifndef PhysicsStructUpdate_Addr
#define PhysicsStructUpdate_Addr 0x1D20B70
#endif
#ifndef PhysicsUnkStructVelocityUpdate_Addr
#define PhysicsUnkStructVelocityUpdate_Addr 0x1D20160
#endif
#ifndef ProcessAirResistance_Addr
#define ProcessAirResistance_Addr 0x1D4D740
#endif
#ifndef ProcessScriptTypes_Addr
#define ProcessScriptTypes_Addr 0x281390
#endif
#ifndef BaseStream_ReadWriteHandleID_Addr
#define BaseStream_ReadWriteHandleID_Addr 0x720670
#endif
#ifndef CBaseRTTIType_VFT_Addr
#define CBaseRTTIType_VFT_Addr 0x311F4D0
#endif
#ifndef CClass_AddEventCallbackType_Addr
#define CClass_AddEventCallbackType_Addr 0x2034E0
#endif
#ifndef CClass_ApplyFlags_Addr
#define CClass_ApplyFlags_Addr 0x206EF0
#endif
#ifndef CClass_SetupScriptCallbacks_Addr
#define CClass_SetupScriptCallbacks_Addr 0x2035C0
#endif
#ifndef CClass_VFT_Addr
#define CClass_VFT_Addr 0x311F2C0
#endif
#ifndef CGameFramework_Systems_120_128_130_Addr
#define CGameFramework_Systems_120_128_130_Addr 0x13B3860
#endif
#ifndef CallbackManager_AddCallback_Addr
#define CallbackManager_AddCallback_Addr 0x2C53EB0
#endif
#ifndef CallbackManager_AddToUnk00_Addr
#define CallbackManager_AddToUnk00_Addr 0x2C53D90
#endif
#ifndef CallbackManager_Unknown1_Addr
#define CallbackManager_Unknown1_Addr 0x2C53850
#endif
#ifndef CallbackManager_Unknown6_Addr
#define CallbackManager_Unknown6_Addr 0x2C54670
#endif
#ifndef GameInstance_GameInstance_Addr
#define GameInstance_GameInstance_Addr                                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: GameInstance_GameInstance_Addr"                      \
              "is 0 - Zoltan found no matches for RED4ext::GameInstance::GameInstance\")")
#endif
#ifndef GameInstance_SetRuntimeScene_Addr
#define GameInstance_SetRuntimeScene_Addr 0x2D9A920
#endif
#ifndef GetGameSystemsData_Addr
#define GetGameSystemsData_Addr 0x2D9DC30
#endif
#ifndef IDynamicStorage_IDynamicStorage_Addr
#define IDynamicStorage_IDynamicStorage_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: IDynamicStorage_IDynamicStorage_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::IDynamicStorage::IDynamicStorage\")")
#endif
#ifndef IGameInstance_RegisterGameLoadCallbacks_Addr
#define IGameInstance_RegisterGameLoadCallbacks_Addr 0x2D9AFD0
#endif
#ifndef IGameInstance_RegisterStreamingWorldLoadedCallback_Addr
#define IGameInstance_RegisterStreamingWorldLoadedCallback_Addr 0x2D9B4F0
#endif
#ifndef IGameInstance_Systems158_Addr
#define IGameInstance_Systems158_Addr 0x2D9B460
#endif
#ifndef IGameInstance_Systems160_Addr
#define IGameInstance_Systems160_Addr 0x2D9B420
#endif
#ifndef IGameInstance_Systems168o170_Addr
#define IGameInstance_Systems168o170_Addr 0x2D9BAF0
#endif
#ifndef IGameInstance_Systems178_Addr
#define IGameInstance_Systems178_Addr 0x2D9AE20
#endif
#ifndef IGameInstance_WorldDetached_Addr
#define IGameInstance_WorldDetached_Addr 0x2D9AD90
#endif
#ifndef IGameInstance_WorldPendingDetach_Addr
#define IGameInstance_WorldPendingDetach_Addr 0x2D9B790
#endif
#ifndef ISerializable_SetOwner_Addr
#define ISerializable_SetOwner_Addr 0x1BA2A0
#endif
#ifndef ISerializable_VFT_Addr
#define ISerializable_VFT_Addr 0x31179A8
#endif
#ifndef IUpdatableSystem_VFT_Addr
#define IUpdatableSystem_VFT_Addr 0x3247C78
#endif
#ifndef LoadGameSystemsData_Addr
#define LoadGameSystemsData_Addr                                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: LoadGameSystemsData_Addr"                            \
              "is 0 - Zoltan found no matches for RED4ext::LoadGameSystemsData\")")
#endif
#ifndef Quaternion_GetYaw_Addr
#define Quaternion_GetYaw_Addr 0x66BC30
#endif
#ifndef Quaternion_ToEulerAngles_Addr
#define Quaternion_ToEulerAngles_Addr 0x567AD0
#endif
#ifndef Quaternion_ToMatrix_Addr
#define Quaternion_ToMatrix_Addr 0x1D3F60
#endif
#ifndef UpdatableSystems_SetRuntimeScene_Addr
#define UpdatableSystems_SetRuntimeScene_Addr 0xBAD3E0
#endif
#ifndef actionActionBase_Lock_Addr
#define actionActionBase_Lock_Addr 0x3D2E30
#endif
#ifndef actionActionBase_StartWithReplicatedState_Addr
#define actionActionBase_StartWithReplicatedState_Addr 0x1B418C0
#endif
#ifndef actionActionInterface_EndActions_Addr
#define actionActionInterface_EndActions_Addr 0x1B5F840
#endif
#ifndef actionActionInterface_IsAnimationiActive_Addr
#define actionActionInterface_IsAnimationiActive_Addr 0x1B5FA10
#endif
#ifndef actionActionInterface_ProcessActions_Addr
#define actionActionInterface_ProcessActions_Addr 0x1B5FB10
#endif
#ifndef audioVehicleMetadata_GetEventData_Addr
#define audioVehicleMetadata_GetEventData_Addr                                                                         \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: audioVehicleMetadata_GetEventData_Addr"              \
              "is 0 - Zoltan found no matches for RED4ext::audio::VehicleMetadata::GetEventData\")")
#endif
#ifndef entComponentsStorage_AddComponent_Addr
#define entComponentsStorage_AddComponent_Addr 0x1067430
#endif
#ifndef entComponentsStorage_AddComponents_Addr
#define entComponentsStorage_AddComponents_Addr 0x1067510
#endif
#ifndef entComponentsStorage_FreeMemory_Addr
#define entComponentsStorage_FreeMemory_Addr 0x1067650
#endif
#ifndef entComponentsStorage_GetComponentByCRUID_Addr
#define entComponentsStorage_GetComponentByCRUID_Addr 0x1067720
#endif
#ifndef entComponentsStorage_GetSize_Addr
#define entComponentsStorage_GetSize_Addr 0x8C0ED0
#endif
#ifndef entComponentsStorage_IsEmpty_Addr
#define entComponentsStorage_IsEmpty_Addr 0x1072C00
#endif
#ifndef entEntity_ReassembleAppearance_Addr
#define entEntity_ReassembleAppearance_Addr 0x1058670
#endif
#ifndef entEntity_SetRuntime_Addr
#define entEntity_SetRuntime_Addr                                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: entEntity_SetRuntime_Addr"                           \
              "is 0 - Zoltan found too many matches for RED4ext::ent::Entity::SetRuntime (2)\")")
#endif
#ifndef entEntity_SetupEntityAndComponents_Addr
#define entEntity_SetupEntityAndComponents_Addr 0x1058550
#endif
#ifndef entEntity_SomethingListeners_Addr
#define entEntity_SomethingListeners_Addr 0x105F400
#endif
#ifndef entIComponent_SetEntity_Addr
#define entIComponent_SetEntity_Addr 0x1065910
#endif
#ifndef entIComponent_VFT_Addr
#define entIComponent_VFT_Addr 0x33472F0
#endif
#ifndef entITransformAttachable_VFT_Addr
#define entITransformAttachable_VFT_Addr 0x324C430
#endif
#ifndef entSlotComponent_GetLocalSlotTransformFromIndex_Addr
#define entSlotComponent_GetLocalSlotTransformFromIndex_Addr 0x116F4D0
#endif
#ifndef entSlotComponent_GetSlotGlobalTransform_Addr
#define entSlotComponent_GetSlotGlobalTransform_Addr 0x116EB70
#endif
#ifndef entSlotComponent_GetSlotIndex_Addr
#define entSlotComponent_GetSlotIndex_Addr 0x116EA20
#endif
#ifndef entSlotComponent_GetSlotLocalTransform_Addr
#define entSlotComponent_GetSlotLocalTransform_Addr 0x116F170
#endif
#ifndef gameGameAudioSystem_SetGlobalParameter_Addr
#define gameGameAudioSystem_SetGlobalParameter_Addr 0x73D3A0
#endif
#ifndef gameGameAudioSystem_UpdateParameter_Addr
#define gameGameAudioSystem_UpdateParameter_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: gameGameAudioSystem_UpdateParameter_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::game::GameAudioSystem::UpdateParameter\")")
#endif
#ifndef gameIGameSystem_SetGameInstance_Addr
#define gameIGameSystem_SetGameInstance_Addr 0xB07FB0
#endif
#ifndef gameIGameSystem_Unset_Addr
#define gameIGameSystem_Unset_Addr 0xB08040
#endif
#ifndef gameIGameSystem_VFT_Addr
#define gameIGameSystem_VFT_Addr 0x3257230
#endif
#ifndef gameObject_CallScriptFunction_Addr
#define gameObject_CallScriptFunction_Addr 0x1416050
#endif
#ifndef physicsColliderSphere_createHandleWithRadius_Addr
#define physicsColliderSphere_createHandleWithRadius_Addr 0x43C8D0
#endif
#ifndef physicsFilterData_LoadPreset_Addr
#define physicsFilterData_LoadPreset_Addr 0x44C170
#endif
#ifndef physicsFilterData_VFT_Addr
#define physicsFilterData_VFT_Addr 0x317ADB0
#endif
#ifndef physicsGeometryCache_FreeAlwaysLoaded_Addr
#define physicsGeometryCache_FreeAlwaysLoaded_Addr 0x451B70
#endif
#ifndef physicsGeometryCache_FreeGeometryKey_Addr
#define physicsGeometryCache_FreeGeometryKey_Addr 0x451E60
#endif
#ifndef physicsGeometryCache_FreeKey_Addr
#define physicsGeometryCache_FreeKey_Addr                                                                              \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsGeometryCache_FreeKey_Addr"                   \
              "is 0 - Zoltan found no matches for RED4ext::physics::GeometryCache::FreeKey\")")
#endif
#ifndef physicsGeometryCache_FreeSector_Addr
#define physicsGeometryCache_FreeSector_Addr 0x452010
#endif
#ifndef physicsGeometryCache_HasGeometryKey_Addr
#define physicsGeometryCache_HasGeometryKey_Addr 0x4521F0
#endif
#ifndef physicsGeometryCache_LoadAlwaysloadedSectorGeometries_Addr
#define physicsGeometryCache_LoadAlwaysloadedSectorGeometries_Addr 0x44FB70
#endif
#ifndef physicsGeometryCache_LoadAlwaysloadedSectorGeometriesSetup_Addr
#define physicsGeometryCache_LoadAlwaysloadedSectorGeometriesSetup_Addr 0x452530
#endif
#ifndef physicsGeometryCache_LoadSectorGeometries_Addr
#define physicsGeometryCache_LoadSectorGeometries_Addr 0x44F570
#endif
#ifndef physicsGeometryCache_LoadSectorGeometriesSetup_Addr
#define physicsGeometryCache_LoadSectorGeometriesSetup_Addr 0x452890
#endif
#ifndef physicsGeometryCache_Unknown_Addr
#define physicsGeometryCache_Unknown_Addr 0x4524C0
#endif
#ifndef physicsGeometryCache_sub_7FF75B921520_Addr
#define physicsGeometryCache_sub_7FF75B921520_Addr 0x450D00
#endif
#ifndef physicsGeometryCache_sub_7FF75B922410_Addr
#define physicsGeometryCache_sub_7FF75B922410_Addr 0x451BF0
#endif
#ifndef physics_GetShapeLocalPos_Addr
#define physics_GetShapeLocalPos_Addr 0x459FE0
#endif
#ifndef physicsProxyCache_AddToCache_Addr
#define physicsProxyCache_AddToCache_Addr 0x47A9A0
#endif
#ifndef physicsProxyCache_GetDataFromCache_Addr
#define physicsProxyCache_GetDataFromCache_Addr 0x4C7A70
#endif
#ifndef physicsProxyCache_GetFromCacheOrGet_Addr
#define physicsProxyCache_GetFromCacheOrGet_Addr 0x47A780
#endif
#ifndef physicsProxyCacheID_DisableCollision_Addr
#define physicsProxyCacheID_DisableCollision_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyCacheID_DisableCollision_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyCacheID::DisableCollision\")")
#endif
#ifndef physicsProxyCacheID_EnableCollision_Addr
#define physicsProxyCacheID_EnableCollision_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyCacheID_EnableCollision_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyCacheID::EnableCollision\")")
#endif
#ifndef physicsProxyCacheManagerUnk948_Kick_Addr
#define physicsProxyCacheManagerUnk948_Kick_Addr 0x4A7730
#endif
#ifndef physicsProxyHelper_Create_Addr
#define physicsProxyHelper_Create_Addr 0x4564F0
#endif
#ifndef physicsProxyHelper_GetThingWithLock_Addr
#define physicsProxyHelper_GetThingWithLock_Addr 0x456460
#endif
#ifndef physicsProxyHelper_SetAngularDamping_Addr
#define physicsProxyHelper_SetAngularDamping_Addr 0x45AFB0
#endif
#ifndef physicsProxyHelper_SetCCD_Addr
#define physicsProxyHelper_SetCCD_Addr 0x45D320
#endif
#ifndef physicsProxyHelper_SetCMassLocalPose_Addr
#define physicsProxyHelper_SetCMassLocalPose_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyHelper_SetCMassLocalPose_Addr"           \
              "is 0 - Zoltan found too many matches for RED4ext::physics::ProxyHelper::SetCMassLocalPose (10)\")")
#endif
#ifndef physicsProxyHelper_SetGravity_Addr
#define physicsProxyHelper_SetGravity_Addr 0x45B8E0
#endif
#ifndef physicsProxyHelper_SetIsQueryable_Addr
#define physicsProxyHelper_SetIsQueryable_Addr 0x45BAE0
#endif
#ifndef physicsProxyHelper_SetLinearDamping_Addr
#define physicsProxyHelper_SetLinearDamping_Addr 0x45BE00
#endif
#ifndef physicsProxyHelper_SetMassAndUpdateInertia_Addr
#define physicsProxyHelper_SetMassAndUpdateInertia_Addr 0x45C200
#endif
#ifndef physicsProxyHelper_SetQueryFilterData_Addr
#define physicsProxyHelper_SetQueryFilterData_Addr 0x45C860
#endif
#ifndef physicsProxyHelper_SetSimulationFilterData_Addr
#define physicsProxyHelper_SetSimulationFilterData_Addr 0x45CC60
#endif
#ifndef physicsProxyHelper_SetSimulationShape_Addr
#define physicsProxyHelper_SetSimulationShape_Addr 0x45BBF0
#endif
#ifndef physicsProxyHelper_Unlock_Addr
#define physicsProxyHelper_Unlock_Addr 0x456570
#endif
#ifndef physicsProxyHelper_UpdateGlobalPose_Addr
#define physicsProxyHelper_UpdateGlobalPose_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyHelper_UpdateGlobalPose_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyHelper::UpdateGlobalPose\")")
#endif
#ifndef physicsProxyHelper_UpdateProxyCache_Addr
#define physicsProxyHelper_UpdateProxyCache_Addr 0x4572D0
#endif
#ifndef physicsProxyID_GetKeyUnk37_0x40_Addr
#define physicsProxyID_GetKeyUnk37_0x40_Addr                                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyID_GetKeyUnk37_0x40_Addr"                \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyID::GetKeyUnk37_0x40\")")
#endif
#ifndef physicsProxyID_GetNbShapes_Addr
#define physicsProxyID_GetNbShapes_Addr                                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyID_GetNbShapes_Addr"                     \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyID::GetNbShapes\")")
#endif
#ifndef physicsProxyID_GetProxy_Addr
#define physicsProxyID_GetProxy_Addr 0x47A920
#endif
#ifndef physicsProxyID_ProcessProxyDesc_Addr
#define physicsProxyID_ProcessProxyDesc_Addr 0x4585D0
#endif
#ifndef physicsProxyID_Something2_Addr
#define physicsProxyID_Something2_Addr                                                                                 \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyID_Something2_Addr"                      \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyID::Something2\")")
#endif
#ifndef physicsProxyID_Unk_Addr
#define physicsProxyID_Unk_Addr 0x4583B0
#endif
#ifndef physicsProxyID_UpdateProxyCacheEntry_Addr
#define physicsProxyID_UpdateProxyCacheEntry_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsProxyID_UpdateProxyCacheEntry_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::physics::ProxyID::UpdateProxyCacheEntry\")")
#endif
#ifndef physics_ProxyID_GetGlobalPose_Addr
#define physics_ProxyID_GetGlobalPose_Addr                                                                             \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physics_ProxyID_GetGlobalPose_Addr"                  \
              "is 0 - Zoltan found too many matches for RED4ext::physics::ProxyID_GetGlobalPose (2)\")")
#endif
#ifndef physicsProxyManager_GetProxyCache_Addr
#define physicsProxyManager_GetProxyCache_Addr 0x479D40
#endif
#ifndef physicsProxyManager_GetProxyHandle_Addr
#define physicsProxyManager_GetProxyHandle_Addr 0x479BF0
#endif
#ifndef physicsProxyManager_HasProxy_Addr
#define physicsProxyManager_HasProxy_Addr 0x479FC0
#endif
#ifndef physicsProxyManager_SetProxyCacheID_Addr
#define physicsProxyManager_SetProxyCacheID_Addr 0x47A330
#endif
#ifndef physicsProxyManager_TestUnk2E2068_Addr
#define physicsProxyManager_TestUnk2E2068_Addr 0x479FC0
#endif
#ifndef physicsVehiclePhysicsInsert1_ReferencePoseSetup_Addr
#define physicsVehiclePhysicsInsert1_ReferencePoseSetup_Addr                                                           \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: physicsVehiclePhysicsInsert1_ReferencePoseSetup_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::physics::VehiclePhysicsInsert1::ReferencePoseSetup\")")
#endif
#ifndef physicsVehiclePhysicsInsert1_SinMath_Addr
#define physicsVehiclePhysicsInsert1_SinMath_Addr 0x1D6D100
#endif
#ifndef physicsVehiclePhysicsInsert2_SetsUnk160Unk15C_Addr
#define physicsVehiclePhysicsInsert2_SetsUnk160Unk15C_Addr 0x1D636E0
#endif
#ifndef physics_pxRigidBody_Get_Addr
#define physics_pxRigidBody_Get_Addr 0x4C7F30
#endif
#ifndef physics_pxRigidBody_Update_Addr
#define physics_pxRigidBody_Update_Addr 0x4C8D50
#endif
#ifndef vehicleAirControl_ApplyTorque_Addr
#define vehicleAirControl_ApplyTorque_Addr 0x1D217B0
#endif
#ifndef vehicleAirControl_GetAngularVelocity_Addr
#define vehicleAirControl_GetAngularVelocity_Addr 0x1D225F0
#endif
#ifndef vehicleAirControl_Process_Addr
#define vehicleAirControl_Process_Addr 0x1D23290
#endif
#ifndef vehicleBaseObject_CheckPhysicsStateActionInterface_Addr
#define vehicleBaseObject_CheckPhysicsStateActionInterface_Addr 0x1C9EB70
#endif
#ifndef vehicleBaseObject_CreateAction_Addr
#define vehicleBaseObject_CreateAction_Addr 0x1C9CC30
#endif
#ifndef vehicleBaseObject_GetCurveSetData_Addr
#define vehicleBaseObject_GetCurveSetData_Addr 0x1C8C940
#endif
#ifndef vehicleBaseObject_GetDeceleration_Addr
#define vehicleBaseObject_GetDeceleration_Addr 0x746530
#endif
#ifndef vehicleBaseObject_GetDisplayName_Addr
#define vehicleBaseObject_GetDisplayName_Addr 0x1C8C700
#endif
#ifndef vehicleBaseObject_GetGravitationalForce_Addr
#define vehicleBaseObject_GetGravitationalForce_Addr 0x1C8C6D0
#endif
#ifndef vehicleBaseObject_GetInverseMass_Addr
#define vehicleBaseObject_GetInverseMass_Addr 0x1C8C6C0
#endif
#ifndef vehicleBaseObject_GetPhysicsData_Addr
#define vehicleBaseObject_GetPhysicsData_Addr 0x746520
#endif
#ifndef vehicleBaseObject_GetTotalMass_Addr
#define vehicleBaseObject_GetTotalMass_Addr 0x1C8C6B0
#endif
#ifndef vehicleBaseObject_GetUnk60C_Addr
#define vehicleBaseObject_GetUnk60C_Addr 0x1C8C6F0
#endif
#ifndef vehicleBaseObject_GetUnk8E0_Addr
#define vehicleBaseObject_GetUnk8E0_Addr 0x1C885B0
#endif
#ifndef vehicleBaseObject_GetVehicleSystem_Addr
#define vehicleBaseObject_GetVehicleSystem_Addr 0x1C8CAC0
#endif
#ifndef vehicleBaseObject_GetWeaponOrientation_Addr
#define vehicleBaseObject_GetWeaponOrientation_Addr 0x1C8CAF0
#endif
#ifndef vehicleBaseObject_HornForDuration_Addr
#define vehicleBaseObject_HornForDuration_Addr 0x1C8D4A0
#endif
#ifndef vehicleBaseObject_HornForDurationDelayed_Addr
#define vehicleBaseObject_HornForDurationDelayed_Addr 0x1C8D700
#endif
#ifndef vehicleBaseObject_PostMovePhysicsStateNotZero_Addr
#define vehicleBaseObject_PostMovePhysicsStateNotZero_Addr 0x1C94310
#endif
#ifndef vehicleBaseObject_PostMovePhysicsStateZero_Addr
#define vehicleBaseObject_PostMovePhysicsStateZero_Addr 0x1C94120
#endif
#ifndef vehicleBaseObject_PreUpdatePreMovePhysicsStateNotZero_Addr
#define vehicleBaseObject_PreUpdatePreMovePhysicsStateNotZero_Addr 0x1C95070
#endif
#ifndef vehicleBaseObject_PreUpdatePreMovePhysicsStateZero_Addr
#define vehicleBaseObject_PreUpdatePreMovePhysicsStateZero_Addr 0x1C94D70
#endif
#ifndef vehicleBaseObject_Reset8B4_Addr
#define vehicleBaseObject_Reset8B4_Addr 0x1C884D0
#endif
#ifndef vehicleBaseObject_SetPhysicsState_Addr
#define vehicleBaseObject_SetPhysicsState_Addr 0x1C9FAE0
#endif
#ifndef vehicleBaseObject_UnsetPhysicsStates_Addr
#define vehicleBaseObject_UnsetPhysicsStates_Addr 0x1C8B800
#endif
#ifndef vehicleBaseObject_UpdatePhysicsSleepState_Addr
#define vehicleBaseObject_UpdatePhysicsSleepState_Addr 0x1C951F0
#endif
#ifndef vehicleBikePhysics_AnimationUpdate_Addr
#define vehicleBikePhysics_AnimationUpdate_Addr 0x1D45C60
#endif
#ifndef vehicleBikePhysics_VFT_Addr
#define vehicleBikePhysics_VFT_Addr 0x34DAD06
#endif
#ifndef vehicleCameraManager_ChangeCamera_Addr
#define vehicleCameraManager_ChangeCamera_Addr 0x1CA7290
#endif
#ifndef vehicleCameraManager_IsTPP_Addr
#define vehicleCameraManager_IsTPP_Addr 0x1CA9610
#endif
#ifndef vehicleCameraManager_ShouldUseSomeListener_Addr
#define vehicleCameraManager_ShouldUseSomeListener_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleCameraManager_ShouldUseSomeListener_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::CameraManager::ShouldUseSomeListener\")")
#endif
#ifndef vehicleCameraManager_Update_Addr
#define vehicleCameraManager_Update_Addr                                                                               \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleCameraManager_Update_Addr"                    \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::CameraManager::Update\")")
#endif
#ifndef vehicleCarPhysics_AnimationUpdate_Addr
#define vehicleCarPhysics_AnimationUpdate_Addr 0x1D4B3E0
#endif
#ifndef vehicleCarPhysics_VFT_Addr
#define vehicleCarPhysics_VFT_Addr 0x34DAEF0
#endif
#ifndef vehicleChassisComponent_BigUpdate_Addr
#define vehicleChassisComponent_BigUpdate_Addr 0x1CB0E90
#endif
#ifndef vehicleChassisComponent_GetCollisionShapes_Addr
#define vehicleChassisComponent_GetCollisionShapes_Addr 0x1CAF450
#endif
#ifndef vehicleChassisComponent_GetProxyHelperAndLock_Addr
#define vehicleChassisComponent_GetProxyHelperAndLock_Addr 0x1CAF0C0
#endif
#ifndef vehicleChassisComponent_SetDampingToPoint4_Addr
#define vehicleChassisComponent_SetDampingToPoint4_Addr                                                                \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleChassisComponent_SetDampingToPoint4_Addr"     \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::ChassisComponent::SetDampingToPoint4\")")
#endif
#ifndef vehicleChassisComponent_SetFilterData_Addr
#define vehicleChassisComponent_SetFilterData_Addr 0x1CAEB80
#endif
#ifndef vehicleChassisComponent_SomethingIfEnabled_Addr
#define vehicleChassisComponent_SomethingIfEnabled_Addr 0x1CB0B10
#endif
#ifndef vehicleChassisComponent_TransformWorldTransform_Addr
#define vehicleChassisComponent_TransformWorldTransform_Addr 0x1CAE750
#endif
#ifndef vehicleChassisComponent_Unknown1_Addr
#define vehicleChassisComponent_Unknown1_Addr                                                                          \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleChassisComponent_Unknown1_Addr"               \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::ChassisComponent::Unknown1\")")
#endif
#ifndef vehicleChassisComponent_Update_Addr
#define vehicleChassisComponent_Update_Addr 0x1CB26C0
#endif
#ifndef vehicleChassisComponent_UpdatePhysicsState_Addr
#define vehicleChassisComponent_UpdatePhysicsState_Addr 0x1CB07C0
#endif
#ifndef vehiclePID_GetCorrection_Addr
#define vehiclePID_GetCorrection_Addr 0x1D48070
#endif
#ifndef vehiclePID_Initialize_Addr
#define vehiclePID_Initialize_Addr 0x1D48080
#endif
#ifndef vehiclePID_Process_Addr
#define vehiclePID_Process_Addr 0x1D480A0
#endif
#ifndef vehiclePID_Reset_Addr
#define vehiclePID_Reset_Addr 0x1D48060
#endif
#ifndef vehiclePID_UpdatePID_Addr
#define vehiclePID_UpdatePID_Addr 0x1D48050
#endif
#ifndef vehiclePersistentDataPS_ResetQuestEnforceTransform_Addr
#define vehiclePersistentDataPS_ResetQuestEnforceTransform_Addr                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehiclePersistentDataPS_ResetQuestEnforceTransform_Addr"\
              "is 0 - Zoltan found no matches for RED4ext::vehicle::PersistentDataPS::ResetQuestEnforceTransform\")")
#endif
#ifndef vehiclePersistentDataPS_UpdateWheelRuntime_Addr
#define vehiclePersistentDataPS_UpdateWheelRuntime_Addr 0x1CE4EE0
#endif
#ifndef vehiclePhysics_ComputeSleep_Addr
#define vehiclePhysics_ComputeSleep_Addr 0x1D2C4D0
#endif
#ifndef vehiclePhysics_GetSomethingWaterParams_Addr
#define vehiclePhysics_GetSomethingWaterParams_Addr 0x1D2AB50
#endif
#ifndef vehiclePhysics_GetVehicle_Addr
#define vehiclePhysics_GetVehicle_Addr 0x377600
#endif
#ifndef vehiclePhysics_IsInAirFromVehicle_func_Addr
#define vehiclePhysics_IsInAirFromVehicle_func_Addr 0x1D52640
#endif
#ifndef vehiclePhysics_LoadHasBeenFlippedOver_Addr
#define vehiclePhysics_LoadHasBeenFlippedOver_Addr 0x1D2B620
#endif
#ifndef vehiclePhysics_ReadWorldTransform_Addr
#define vehiclePhysics_ReadWorldTransform_Addr 0x1D2A7E0
#endif
#ifndef vehiclePhysics_SetUnkA0ToOne_Addr
#define vehiclePhysics_SetUnkA0ToOne_Addr 0x1D2B750
#endif
#ifndef vehiclePhysics_UpdateDataWorldTransform_Addr
#define vehiclePhysics_UpdateDataWorldTransform_Addr 0x1D2A5A0
#endif
#ifndef vehiclePhysics_VFT_Addr
#define vehiclePhysics_VFT_Addr 0x34DA9A8
#endif
#ifndef vehiclePhysicsData_AddTorque_Addr
#define vehiclePhysicsData_AddTorque_Addr 0x1D1FEB0
#endif
#ifndef vehiclePhysicsData_ApplyForceAtPosition_Addr
#define vehiclePhysicsData_ApplyForceAtPosition_Addr 0x1D1FCD0
#endif
#ifndef vehiclePhysicsData_ApplyTorqueAtPosition_Addr
#define vehiclePhysicsData_ApplyTorqueAtPosition_Addr 0x1D1F6D0
#endif
#ifndef vehiclePhysicsData_SetUsesNormalChassisMass_Addr
#define vehiclePhysicsData_SetUsesNormalChassisMass_Addr 0x1D20130
#endif
#ifndef vehiclePhysicsData_UpdateChassis_Addr
#define vehiclePhysicsData_UpdateChassis_Addr 0x1D1FDF0
#endif
#ifndef vehiclePhysicsData_UsesAlternativeChassisMass_Addr
#define vehiclePhysicsData_UsesAlternativeChassisMass_Addr 0x1D20760
#endif
#ifndef vehicleTPPCameraComponent_GetLocationFromOffset_Addr
#define vehicleTPPCameraComponent_GetLocationFromOffset_Addr 0x1D036A0
#endif
#ifndef vehicleTPPCameraComponent_GetYaw_Addr
#define vehicleTPPCameraComponent_GetYaw_Addr 0x1D081A0
#endif
#ifndef vehicleTPPCameraComponent_TargetedCameraInterface_Update_Addr
#define vehicleTPPCameraComponent_TargetedCameraInterface_Update_Addr 0x1D06C40
#endif
#ifndef vehicleTPPCameraComponent_TargetedCameraInterface_sub_58_Addr
#define vehicleTPPCameraComponent_TargetedCameraInterface_sub_58_Addr 0x1D04E00
#endif
#ifndef vehicleTPPCameraComponent_UpdateData_Addr
#define vehicleTPPCameraComponent_UpdateData_Addr 0x1D06600
#endif
#ifndef vehicleTPPCameraComponent_UpdatePitch_Addr
#define vehicleTPPCameraComponent_UpdatePitch_Addr 0x1D087A0
#endif
#ifndef vehicleTPPCameraComponent_UpdatePosition_Addr
#define vehicleTPPCameraComponent_UpdatePosition_Addr 0x1D07360
#endif
#ifndef vehicleTPPCameraComponent_UpdateTPP_Addr
#define vehicleTPPCameraComponent_UpdateTPP_Addr                                                                       \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleTPPCameraComponent_UpdateTPP_Addr"            \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::TPPCameraComponent::UpdateTPP\")")
#endif
#ifndef vehicleTankPhysics_VFT_Addr
#define vehicleTankPhysics_VFT_Addr 0x34DB930
#endif
#ifndef vehicleUnk568_CopyOverCollisionForce_Addr
#define vehicleUnk568_CopyOverCollisionForce_Addr 0x1AF3600
#endif
#ifndef vehicleUnk568_SetAcceleration_Addr
#define vehicleUnk568_SetAcceleration_Addr 0x1AF3640
#endif
#ifndef vehicleUnk568_SetLinearVelocityEtc_Addr
#define vehicleUnk568_SetLinearVelocityEtc_Addr 0x1AF3890
#endif
#ifndef vehicleUnk568_SetUnkD0_Addr
#define vehicleUnk568_SetUnkD0_Addr 0x1AF3620
#endif
#ifndef vehicleUnk570_GetCollisionFxForMaterial_Addr
#define vehicleUnk570_GetCollisionFxForMaterial_Addr 0x1D36B90
#endif
#ifndef vehicleUnk570_GetFxForMaterial_Addr
#define vehicleUnk570_GetFxForMaterial_Addr 0x1D36D10
#endif
#ifndef vehicleUnk570_GetSmearFxForMaterial_Addr
#define vehicleUnk570_GetSmearFxForMaterial_Addr 0x1D36C80
#endif
#ifndef vehicleUnk570_ProcessEffects_Addr
#define vehicleUnk570_ProcessEffects_Addr 0x1D3CD30
#endif
#ifndef vehicleUnk570_ProcessImpactScratch_Addr
#define vehicleUnk570_ProcessImpactScratch_Addr 0x1D38440
#endif
#ifndef vehicleUnk570_Setup_Addr
#define vehicleUnk570_Setup_Addr 0x1D3A580
#endif
#ifndef vehicleUnk570_SkidMarkEffectStart_Addr
#define vehicleUnk570_SkidMarkEffectStart_Addr 0x1D3D900
#endif
#ifndef vehicleUnk570_TireTrackEffectStart_Addr
#define vehicleUnk570_TireTrackEffectStart_Addr 0x1D3E260
#endif
#ifndef vehicleUnk570_UpdateEffectsBlackboard_Addr
#define vehicleUnk570_UpdateEffectsBlackboard_Addr 0x1D39BB0
#endif
#ifndef vehicleUnk570_WheelEffectUpdate_Addr
#define vehicleUnk570_WheelEffectUpdate_Addr 0x1D3CD30
#endif
#ifndef vehicleUnk580_GetAudioResourceMetadata_Addr
#define vehicleUnk580_GetAudioResourceMetadata_Addr 0x1C763D0
#endif
#ifndef vehicleUnk580_IsRadioReceiverActive_Addr
#define vehicleUnk580_IsRadioReceiverActive_Addr 0x1C77180
#endif
#ifndef vehicleUnk580_NextRadioReceiverStation_Addr
#define vehicleUnk580_NextRadioReceiverStation_Addr 0x1C79A90
#endif
#ifndef vehicleUnk580_SetRadioTier_Addr
#define vehicleUnk580_SetRadioTier_Addr 0x1C79BD0
#endif
#ifndef vehicleUnk580_ShouldUseSomeAVListener_Addr
#define vehicleUnk580_ShouldUseSomeAVListener_Addr 0x1C75E10
#endif
#ifndef vehicleUnk580_ToggleHorn_Addr
#define vehicleUnk580_ToggleHorn_Addr 0x1C77A00
#endif
#ifndef vehicleUnk580_Update_Addr
#define vehicleUnk580_Update_Addr 0x1C7B3A0
#endif
#ifndef vehicleUnk580_Update3CA_Addr
#define vehicleUnk580_Update3CA_Addr 0x1C793B0
#endif
#ifndef vehicleUnk580_UpdateEvents_Addr
#define vehicleUnk580_UpdateEvents_Addr 0x1C7D0A0
#endif
#ifndef vehicleUnk580_UpdateTPPinAudioSystem_Addr
#define vehicleUnk580_UpdateTPPinAudioSystem_Addr                                                                      \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: vehicleUnk580_UpdateTPPinAudioSystem_Addr"           \
              "is 0 - Zoltan found no matches for RED4ext::vehicle::Unk580::UpdateTPPinAudioSystem\")")
#endif
#ifndef vehicleUnk580_UpdateTireParameters_Addr
#define vehicleUnk580_UpdateTireParameters_Addr 0x1C75370
#endif
#ifndef vehicleUnk580_UpdateWheelEmitters_Addr
#define vehicleUnk580_UpdateWheelEmitters_Addr 0x1C7B010
#endif
#ifndef vehicleUnk588_Unknown_Addr
#define vehicleUnk588_Unknown_Addr 0x1C7EE20
#endif
#ifndef vehicleUnk588_UpdateTransform_Addr
#define vehicleUnk588_UpdateTransform_Addr 0x1C7FC10
#endif
#ifndef vehicleUnkD10_Reset_Addr
#define vehicleUnkD10_Reset_Addr 0x1D512D0
#endif
#ifndef vehicleWheeledPhysics_ApplyWaterResistance_Addr
#define vehicleWheeledPhysics_ApplyWaterResistance_Addr 0x1D69D90
#endif
#ifndef vehicleWheeledPhysics_FixedUpdate_Addr
#define vehicleWheeledPhysics_FixedUpdate_Addr 0x1D51190
#endif
#ifndef vehicleWheeledPhysics_FourWheelTorque_Addr
#define vehicleWheeledPhysics_FourWheelTorque_Addr 0x1D4DA20
#endif
#ifndef vehicleWheeledPhysics_FourWheelTorqueStuff_Addr
#define vehicleWheeledPhysics_FourWheelTorqueStuff_Addr 0x1D4EDD0
#endif
#ifndef vehicleWheeledPhysics_GetEnergy_Addr
#define vehicleWheeledPhysics_GetEnergy_Addr 0x1D51F50
#endif
#ifndef vehicleWheeledPhysics_GetNumberOfWheelsTouchingGround_Addr
#define vehicleWheeledPhysics_GetNumberOfWheelsTouchingGround_Addr 0x1D520C0
#endif
#ifndef vehicleWheeledPhysics_ProcessAirControl_Addr
#define vehicleWheeledPhysics_ProcessAirControl_Addr 0x1D298C0
#endif
#ifndef vehicleWheeledPhysics_SetIsMovingOthers_Addr
#define vehicleWheeledPhysics_SetIsMovingOthers_Addr 0x1D2BEA0
#endif
#ifndef vehicleWheeledPhysics_SetupInsert_Addr
#define vehicleWheeledPhysics_SetupInsert_Addr 0x1D56C60
#endif
#ifndef vehicleWheeledPhysics_SomethingWheelRayTrace_Addr
#define vehicleWheeledPhysics_SomethingWheelRayTrace_Addr 0x1D532A0
#endif
#ifndef vehicleWheeledPhysics_SomethingWheels_Addr
#define vehicleWheeledPhysics_SomethingWheels_Addr 0x1D57E80
#endif
#ifndef vehicleWheeledPhysics_TurningRollFactorStuff_Addr
#define vehicleWheeledPhysics_TurningRollFactorStuff_Addr 0x1D57060
#endif
#ifndef vehicleWheeledPhysics_Unk15CStuff_Addr
#define vehicleWheeledPhysics_Unk15CStuff_Addr 0x1D51CD0
#endif
#ifndef vehicleWheeledPhysics_Update_Addr
#define vehicleWheeledPhysics_Update_Addr 0x1D57AC0
#endif
#ifndef vehicleWheeledPhysics_UpdatePassengerAnim_Addr
#define vehicleWheeledPhysics_UpdatePassengerAnim_Addr 0x1D50BA0
#endif
#ifndef vehicleWheeledPhysics_VFT_Addr
#define vehicleWheeledPhysics_VFT_Addr 0x34DB1B8
#endif
#ifndef worldEffectBlackboard_SetValue_Addr
#define worldEffectBlackboard_SetValue_Addr                                                                            \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: worldEffectBlackboard_SetValue_Addr"                 \
              "is 0 - Zoltan found too many matches for RED4ext::world::EffectBlackboard::SetValue (2)\")")
#endif
#ifndef worldRuntimeScene_SetupWithLogging_Addr
#define worldRuntimeScene_SetupWithLogging_Addr 0xB97840
#endif
#ifndef worldRuntimeSystemPhysics_FreeGeos_Addr
#define worldRuntimeSystemPhysics_FreeGeos_Addr                                                                        \
    0 _Pragma("message(__FILE__ \"(\" __LINE_STR__ \") : Warning: worldRuntimeSystemPhysics_FreeGeos_Addr"             \
              "is 0 - Zoltan found no matches for RED4ext::world::RuntimeSystemPhysics::FreeGeos\")")
#endif
#ifndef RollFactorTorqueThing_Addr
#define RollFactorTorqueThing_Addr 0x1D6E3E0
#endif
#ifndef SetLocalizedTextString_Addr
#define SetLocalizedTextString_Addr 0x709460
#endif
#ifndef TPPCameraStatsUpdate_Addr
#define TPPCameraStatsUpdate_Addr 0x1D06600
#endif
#ifndef VehicleHelperUpdate_Addr
#define VehicleHelperUpdate_Addr 0x1D51500
#endif
#ifndef VehiclePhysicsUpdate_Addr
#define VehiclePhysicsUpdate_Addr 0x1D4EFC0
#endif
#ifndef VehicleProcessWeapons_Addr
#define VehicleProcessWeapons_Addr 0x1C9F220
#endif
#ifndef VehicleUpdateOrientationWithPID_Addr
#define VehicleUpdateOrientationWithPID_Addr 0x1CACFD0
#endif
