file(GLOB_RECURSE UNINSTALL_FILES "${LTBF_GAME_DIR}/*" LIST_DIRECTORIES false)
# list(FILTER UNINSTALL_FILES EXCLUDE REGEX "uninstall")

set(LTBF_INSTALLED_FILES_REL "")
foreach(_FILE ${UNINSTALL_FILES})
  file(RELATIVE_PATH _TEMPFILE "${LTBF_INSTALL_LOCATION}" "${_FILE}")
  file(TO_NATIVE_PATH "${_TEMPFILE}" REAL_FILE)
  list(APPEND LTBF_INSTALLED_FILES_REL "${REAL_FILE}")
endforeach()

list(JOIN LTBF_INSTALLED_FILES_REL " " LTBF_INSTALLED_FILES)

file(GLOB_RECURSE UNINSTALL_FOLDERS "${LTBF_GAME_DIR}/*" LIST_DIRECTORIES true)
list(FILTER UNINSTALL_FOLDERS INCLUDE REGEX "/let_there_be_flight/")

set(LTBF_INSTALLED_FOLDERS_REL "")
foreach(_FOLDER ${UNINSTALL_FOLDERS})
  file(RELATIVE_PATH _TEMPFILE "${LTBF_INSTALL_LOCATION}" "${_FOLDER}")
  get_filename_component(_TEMPFOLDER ${_TEMPFILE} DIRECTORY)
  file(TO_NATIVE_PATH "${_TEMPFOLDER}" REAL_FOLDER)
  list(APPEND LTBF_INSTALLED_FOLDERS_REL "${REAL_FOLDER}")
endforeach()

list(REMOVE_DUPLICATES LTBF_INSTALLED_FOLDERS_REL)
list(JOIN LTBF_INSTALLED_FOLDERS_REL " " LTBF_INSTALLED_FOLDERS)

configure_file("${LTBF_UNINSTALL_BAT_IN}" "${LTBF_UNINSTALL_BAT_OUT}")