function(target_output_directory TARGET DIRECTORY)
 foreach(CONFIGURATION ${CMAKE_CONFIGURATION_TYPES})
    string(TOUPPER ${CONFIGURATION} CONFIGURATION_UPPER)

    set_target_properties(${TARGET}
      PROPERTIES
        ARCHIVE_OUTPUT_DIRECTORY_${CONFIGURATION_UPPER} "${CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CONFIGURATION_UPPER}}/${DIRECTORY}"
        LIBRARY_OUTPUT_DIRECTORY_${CONFIGURATION_UPPER} "${CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CONFIGURATION_UPPER}}/${DIRECTORY}"
        RUNTIME_OUTPUT_DIRECTORY_${CONFIGURATION_UPPER} "${CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CONFIGURATION_UPPER}}/${DIRECTORY}"
    )
  endforeach()
endfunction()
